name: Lint

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          fail_on_error: true
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
